pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    
    tools {nodejs "nodejs"}

    environment {
        //once you sign up for Docker hub, use that user_id here
        registry = "jwhitbread/jmcreative:dev"
        //- update your credentials ID after creating credentials for connecting to Docker Hub
        registryCredential = 'DockerHub'
        dockerImage = ''
    }
    
    stages {
        stage('Cloning Git') {
            steps {
                //define scm connection for polling
                //define scm connection for polling
                checkout([$class: 'GitSCM', branches: [[name: '*/dev']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'jenkins-github-ssh', url: 'https://github.com/JordanW94/jmcreative']]])
            }
        }

    // Install dependencies
    stage('Install dependencies') {
      steps{
        dir('app'){
          sh 'npm install && npm run compile:scss'
        }
      }
    }

    // Remove node_modules
    stage('Remove node_modules') {
      steps{
        dir('app'){
          sh 'rm -r node_modules/'
        }
      }
    }
    
    // Building Docker images
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry
        }
      }
    }
    
     // Uploading Docker images into Docker Hub
    stage('Upload Image') {
     steps{    
         script {
            docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            }
        }
      }
    }
    
  }
}